esphome:
  name: fireremote
  platform: ESP32
  board: m5stack-fire
  # on_boot:
  #   priority: 600.0
  #   then:
  #     - delay: 45s
  #     - if:
  #         condition:
  #           not:
  #             - wifi.connected:
  #         then:
  #           - switch.turn_on: sleep_toggle
logger:
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_fallback_password

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
      # type: local
      # path: ../ssieb_custom_components/components
    components: [ ip5306 ]

packages:
  # home_media_player: !include homeConfig/media_player_light.yaml
  # home_text_sensor: !include homeConfig/text_sensor.yaml
  # home_light: !include homeConfig/light.yaml
  # home_switch: !include homeConfig/switch.yaml
  # ip5306: !include ../homeThing/common/m5stack-fire/ip5306.yaml
  # device_base: !include ../homeThing/common/device_base.yaml
  # fonts: !include ../homeThing/common/fonts.yaml
  # icon_fonts: !include ../homeThing/common/icon_fonts.yaml
  # images: !include ../homeThing/common/images.yaml
  # settings: !include ../homeThing/common/settings.yaml
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [
      common/m5stack-fire/ip5306.yaml, # power management and screen backlight
      # common/m5stack-fire/sleep.yaml, # deep sleep
      # common/m5stack-fire/binary_sensor.yaml, # buttons
      common/m5stack-fire/backlight.yaml, # backlight
      common/m5stack-fire/sidelight.yaml, # sidelight
      # common/UnitEncoderC.yaml, # encoder
    ]
    refresh: 0s

binary_sensor:
  - platform: gpio
    id: M5_BtnB
    pin:
      number: 38
      inverted: true
    on_multi_click:
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - media_player.toggle: media_player_out
      - timing:
          - ON FOR AT LEAST 350ms
        then:
          - voice_assistant.start:
      - timing:
          - ON FOR AT LEAST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - voice_assistant.stop:

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

i2s_audio:
  i2s_lrclk_pin: GPIO13
  i2s_bclk_pin: GPIO32
  i2s_mclk_pin: GPIO0

microphone:
  - platform: i2s_audio
    adc_pin: GPIO34
    adc_type: internal
    id: adc_mic

media_player:
  - platform: i2s_audio
    name: "${friendly_name} Internal Media Player"
    id: media_player_out
    dac_type: internal
    mode: right

voice_assistant:
  microphone: adc_mic
  on_start:
    # - media_player.stop:
    #     id: media_player_out
    - light.turn_on:
        id: side_light
        blue: 100%
        red: 0%
        green: 0%
        effect: none
  on_tts_start:
    - light.turn_on:
        id: side_light
        blue: 60%
        red: 20%
        green: 20%
        effect: none
  on_tts_end:
    # - media_player.play_media:
    #     id: media_player_out
    #     media_url: !lambda return x;
    - light.turn_on:
        id: side_light
        blue: 60%
        red: 20%
        green: 20%
        effect: pulse
  on_end:
    # - delay: 1s
    # - wait_until:
    #     not:
    #       media_player.is_playing: media_player_out
    - light.turn_off: side_light
  on_error:
    - light.turn_on:
        id: side_light
        blue: 0%
        red: 100%
        green: 0%
        effect: none
    - delay: 1s
    - light.turn_off: side_light
  
display:
  - platform: ili9xxx
    model: M5STACK
    cs_pin: 14
    dc_pin: 27
    reset_pin: 33
    id: my_display
    update_interval: 3600s
    lambda: |-
      // id(homeThingMenu)->draw_menu_screen();
      return;
