esphome:
  name: fireremote
  platform: ESP32
  board: m5stack-fire
  on_boot:
    priority: 600.0
    then:
      - delay: 45s
      - if:
          condition:
            not:
              - wifi.connected:
          then:
            - switch.turn_on: sleep_toggle

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_fallback_password

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
    components: [ ip5306 ]
  - source:
    #   type: git
    #   url: https://github.com/landonr/homeThing
    #   ref: main
    # refresh: 0s
      type: local
      path: ../homeThing/components
    components: [homeThing]
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
    refresh: 0s
      # type: local
      # path: ../local_components/components
    components: [
      homeassistant_component,
      homeassistant_media_player,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]
  - source:
      type: local
      path: ../local_components/components
    components: [
      UnitEncoderC
    ]

packages:
  device_base: !include ../homeThing/common/device_base.yaml
  home_media_player: !include homeConfig/media_player.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  fonts: !include ../homeThing/common/fonts.yaml
  icon_fonts: !include ../homeThing/common/icon_fonts.yaml
  # images: !include ../homeThing/common/images.yaml
  settings: !include ../homeThing/common/settings.yaml

substitutions:
  friendly_name: "homeThingFireRemote"
  large_heavy_font_size: "24"
  large_font_size: "24"
  medium_font_size: "20"
  small_font_size: "18"
  home_thing_logo_size: "64"
  material_font_large_size: "28"
  material_font_small_size: "24"

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: True
  - id: bus_b
    sda: GPIO0
    scl: GPIO26
    scan: true

UnitEncoderC:
  id: encoder_base
  i2c_id: bus_a
  button:
    name: "${friendly_name} Rotary Button"
    id: rotary_button
    internal: True
    on_press:
      then:
        - lambda: |-
            id(homeThingMenu)->buttonPressSelect();
  encoder:
    name: "${friendly_name} Rotary Encoder"
    id: rotary
    internal: True
    encoder_filter: 2
    on_clockwise:
      - lambda: |-
          id(homeThingMenu)->buttonPressWakeUpDisplay();
          id(homeThingMenu)->rotaryScrollClockwise(id(rotary).state);
    on_anticlockwise:
      - lambda: |-
          id(homeThingMenu)->buttonPressWakeUpDisplay();
          id(homeThingMenu)->rotaryScrollCounterClockwise(id(rotary).state);

ip5306:
  i2c_id: bus_a
  battery_level:
    name: ${friendly_name} Battery Percent
    id: battery_percent
  charger_connected:
    internal: true
    id: connected
  charge_full:
    id: full
    internal: true

deep_sleep:
  id: deep_sleep_
  wakeup_pin: 39
  wakeup_pin_mode: INVERT_WAKEUP

binary_sensor:
  - platform: gpio
    id: M5_BtnA
    pin:
      number: 39
      inverted: true
    on_click:
      then:
        - lambda: |-
            id(homeThingMenu)->rotaryScrollCounterClockwise(0);
  - platform: gpio
    id: M5_BtnB
    pin:
      number: 38
      inverted: true
    on_click:
      then:
        - lambda: |-
           id(homeThingMenu)->buttonPressSelect();
  - platform: gpio
    id: M5_BtnC
    pin:
      number: 37
      inverted: true
    on_press:
      - voice_assistant.start:
    on_release:
      - voice_assistant.stop:
    # on_click:
    #   then:
    #     - lambda: |-
    #         id(homeThingMenu)->rotaryScrollClockwise(0);

# We can still control the backlight independently
switch:
  - platform: template
    name: ${friendly_name} Sleep Toggle
    id: sleep_toggle
    optimistic: true
    on_turn_on:
      then:
        - deep_sleep.enter:
            id: deep_sleep_

output:
  - platform: ledc
    pin: 32
    id: gpio_32_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_32_backlight_pwm
    name: ${friendly_name} Backlight
    id: backlight
    restore_mode: ALWAYS_ON
  - platform: fastled_clockless
    chipset: SK6812
    pin: GPIO15
    num_leds: 10
    rgb_order: GRB
    id: side_light
    name: ${friendly_name} Remote Light
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    effects:
      - addressable_rainbow:
          name: Rainbow Effect
          speed: 20
          width: 15

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

cover:
  - platform: homeassistant_component
    entity_id: "cover.megadesk_cover"
    name: "Megadesk"
    id: cover_megadesk

homeThing:
  id: homeThingMenu
  settings:
    mode: rotary
    menu_rollback: true
    menu_rollover: true
  sleep_switch: sleep_toggle
  backlight: backlight
  battery:
    battery_percent: battery_percent
    charging: connected
  media_player_group: media_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo
    header_height: 24
    margin_size: 8
    slider_margin_size: 6
    scroll_bar_width: 8
    bottom_bar_margin: 8
    now_playing_max_lines: 5
    draw_now_playing_bottom_menu: true
    draw_battery_level: true
    dark_mode: true
    draw_volume_level: false
    draw_header_time: true
  screens:
    - name: Desk Screen
      entities:
        - type: cover
          id: cover_megadesk
        - type: command
          name: "desk nudge up"
          command:
            - homeassistant.service:
                service: button.press
                data:
                  entity_id: "button.desk_position_nudge_up"
        - type: command
          name: "desk nudge down"
          command:
            - homeassistant.service:
                service: button.press
                data:
                  entity_id: "button.desk_position_nudge_down"
        - id: light_desk_lamp
          type: light
    - name: Settings Screen
      show_version: True
      entities:
        - id: side_light
          type: light
        - id: backlight
          type: light
        - id: "restart_switch"
          type: switch
        - id: wifi_ssid
          type: text_sensor
        - id: wifi_signal_percent
          type: sensor
        - id: wifi_ip
          type: text_sensor

display:
  - platform: ili9xxx
    model: M5STACK
    cs_pin: 14
    dc_pin: 27
    reset_pin: 33
    id: my_display
    update_interval: 3600s 
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;

i2s_audio:
  i2s_lrclk_pin: GPIO15
  # i2s_bclk_pin: GPIO35

microphone:
  - platform: i2s_audio
    id: adc_mic
    adc_type: internal
    adc_pin: GPIO34

speaker:
  - platform: i2s_audio
    dac_type: internal
    i2s_dout_pin: GPIO25
    mode: right
    id: speaker_id

voice_assistant:
  microphone: adc_mic
  speaker: speaker_id