esphome:
  name: "homething-lilygo"
  platform: ESP32
  board: featheresp32
  on_boot:
    priority: 600.0
    then:
      - delay: 45s
      - if:
          condition:
            not:
              - wifi.connected:
          then:
            - switch.turn_on: sleep_toggle

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_fallback_password

external_components:
  - source:
      type: git
      url: https://github.com/landonr/homeThing
      ref: main
    refresh: 0s
      # type: local
      # path: ../homeThing/components
    components: [homeThing]
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
    refresh: 0s
      # type: local
      # path: ../local_components/components
    components: [
      homeassistant_component,
      homeassistant_media_player,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]
  - source: github://pr#5214 # used to load images on compile
    components: [ image ]
  - source: github://pr#5254 # used to load fonts on compile
    components: [ font, external_files ]

packages:
  home_media_player: !include homeConfig/media_player.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  # device_base: !include ../homeThing/../homeThing/common/device_base.yaml
  # ipod_control_backlight: !include ../homeThing/../homeThing/common/ipod/lilygo_tdisplay_ipod_backlight.yaml
  # ipod_control_battery: !include ../homeThing/../homeThing/common/ipod/lilygo_tdisplay_ipod_battery.yaml
  # ipod_control_binary_sensor: !include ../homeThing/../homeThing/common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml
  # ipod_control_rotary: !include ../homeThing/../homeThing/common/ipod/lilygo_tdisplay_ipod_rotary.yaml
  # ipod_control_sleep: !include ../homeThing/../homeThing/common/ipod/lilygo_tdisplay_ipod_sleep.yaml
  # fonts: !include ../homeThing/../homeThing/common/fonts.yaml
  # icon_fonts: !include ../homeThing/../homeThing/common/icon_fonts.yaml
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [
      common/device_base.yaml, # defines api, ota, free memory and uptime sensor
      common/ipod/lilygo_tdisplay_ipod_backlight.yaml, # used for toggling backlight
      common/ipod/lilygo_tdisplay_ipod_battery.yaml, # used for battery percent
      common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml, # used for button controls
      common/ipod/lilygo_tdisplay_ipod_rotary.yaml, # used for rotary controls
      common/ipod/lilygo_tdisplay_ipod_sleep.yaml, # required for device to sleep
      common/fonts.yaml, # default font
      common/icon_fonts.yaml, # material icons
      common/images.yaml # boot screen image
    ]
    refresh: 0s

substitutions:
  friendly_name: "homeThingClear"

color:
  - id: my_red
    red_int: 197
    green_int: 43
    blue_int: 48
  - id: my_green
    red_int: 120
    green_int: 191
    blue_int: 26
  - id: my_blue
    red_int: 129
    green_int: 196
    blue_int: 255
  - id: my_yellow
    red_int: 255
    green_int: 204
    blue_int: 0
  - id: my_primary_accent
    red_int: 22
    green_int: 88
    blue_int: 142

homeThing:
  id: homeThingMenu
  settings:
    sleep_after: 14400
  sleep_switch: sleep_toggle
  backlight: backlight
  battery:
    battery_percent: battery_percent
    charging: charging
  media_player_group: media_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    colors:
      accent_primary: my_primary_accent
      red: my_red
      green: my_green
      blue: my_blue
      yellow: my_yellow
    draw_battery_level: true
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    launch_image: launch_image

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90
    update_interval: 10s
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;
