esphome:
  name: "lilygos3"
  platformio_options:
    board_build.f_flash: 80000000L
    board_upload.flash_size: 16MB
    board_build.partitions: default_16MB.csv
    board_build.arduino.memory_type: qio_opi

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S3 Fallback Hotspot"
    password: "zQ9tuPKIfFMu"

external_components:
  - source:
    #   type: git
    #   url: https://github.com/landonr/homeThing
    #   ref: main
      type: local
      path: ../homething/components
    refresh: 0s
    components: [homeThing]
  - source:
    #   type: git
    #   url: https://github.com/landonr/esphome-components
    #   ref: main
    # refresh: 0s
      type: local
      path: ../local_components/components
    refresh: 0s
    components: [
      homeassistant_component,
      homeassistant_media_player,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]
  - source: github://landonr/lilygo-tdisplays3-esphome
    components: [tdisplays3]

packages:
  device_base: !include ../homeThing/common/device_base.yaml
  settings: !include ../homeThing/common/settings.yaml
  home_media_player: !include homeConfig/media_player.yaml
  home_switch: !include homeConfig/switch.yaml
  fonts: !include ../homeThing/common/fonts.yaml
  icon_fonts: !include ../homeThing/common/icon_fonts.yaml
  images: !include ../homeThing/common/images.yaml
  ipod_control_binary_sensor: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml
  ipod_control_rotary: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_rotary.yaml
  ipod_control_battery: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_battery.yaml
  ipod_control_sleep: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_sleep.yaml

substitutions:
  friendly_name: "s3 homething"
  rotary_left_pin: "2"
  rotary_right_pin: "10"
  rotary_up_pin: "3"
  rotary_down_pin: "1"
  rotary_select_pin: "11"
  rotary_pin_a: "13"
  rotary_pin_b: "12"
  screen_left_pin: "GPIO0"
  screen_right_pin: "GPIO14"
  battery_pin: "4"

output:
  - platform: ledc
    pin: GPIO38
    id: gpio38
    frequency: 2000

remote_transmitter:
  pin: GPIO21
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

light:
  - platform: monochromatic
    output: gpio38
    name: "Backlight"
    id: backlight
    restore_mode: RESTORE_DEFAULT_ON
  - platform: homeassistant_component
    id: light_desk_lamp
    entity_id: light.desk_lamp
    name: Desk Lamp
  - platform: homeassistant_component
    id: light_all_lights
    entity_id: light.all_lights
    name: All Lights
  - platform: homeassistant_component
    id: light_rgb_lights
    entity_id: light.rgb_lights
    name: Color Lights 

display:
  - platform: tdisplays3
    id: my_display
    rotation: 180
    update_interval: 10s
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;

cover:
  - platform: homeassistant_component
    entity_id: "cover.megadesk_cover"
    name: "Megadesk"
    id: cover_megadesk

switch:
  - platform: gpio
    pin: GPIO15
    name: "BacklightBattery"
    id: backlightBattery
    internal: true
    restore_mode: ALWAYS_ON   

homeThing:
  id: homeThingMenu
  settings:
    sleep_after: 14400
  # sleep_switch: sleep_toggle
  backlight: backlight
  header:
    time_id: esptime
  sleep_switch: sleep_toggle
  battery:
    battery_percent: battery_percent
    charging: charging
  media_player_group: media_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    draw_battery_level: true
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    launch_image: launch_image
  screens:
    - name: Desk Screen
      entities:
        - type: command
          name: "cat toy forward"
          command:
          - remote_transmitter.transmit_pronto:
              repeat:
                times: 5
                wait_time: 10ms
              data: "0000 006D 0022 0000 0143 00A0 0015 0014 0015 0014 0015 0014 0015 0014 0015 0014 0015 0014 0015 0014 0015 0014 0015 003A 0015 003A 0015 003A 0015 003A 0015 003A 0015 003A 0015 003A 0015 003A 0015 0014 0015 0014 0015 0014 0015 0014 0015 0014 0015 0014 0015 0014 0015 0014 0015 003A 0015 003A 0015 003A 0015 003A 0015 003A 0015 003A 0015 003A 0015 003A 0015 06C3"
        - type: command
          name: "cat toy back"
          command:
          - remote_transmitter.transmit_pronto:
              repeat:
                times: 5
                wait_time: 10ms
              data: "0000 006D 0022 0000 0145 009D 0017 0011 0018 0011 0018 0011 0018 0011 0017 0011 0018 0011 0018 0011 0018 0011 0017 0037 0018 0037 0017 0037 0017 0037 0017 0037 0017 0037 0017 0037 0017 0037 0017 0011 0018 0011 0017 0011 0017 0011 0017 0037 0017 0037 0017 0011 0017 0011 0017 0037 0017 0037 0017 0037 0017 0037 0017 0011 0018 0011 0017 0037 0018 0036 0019 06C3"
        - type: cover
          id: cover_megadesk
        - type: command
          name: "desk nudge up"
          command:
            - homeassistant.service:
                service: button.press
                data:
                  entity_id: "button.mega_homething_desk_position_nudge_up"
        - type: command
          name: "desk nudge down"
          command:
            - homeassistant.service:
                service: button.press
                data:
                  entity_id: "button.mega_homething_desk_position_nudge_down"
        - id: light_desk_lamp
          type: light
    - name: Lights Screen
      entities:
        - id: light_all_lights
          type: light
        - id: light_rgb_lights
          type: light
        - type: command
          name: "color lights"
          command:
            - homeassistant.service:
                service: script.colors
        - type: command
          name: "hell lights"
          command:
            - homeassistant.service:
                service: scene.turn_on
                data:
                  entity_id: "scene.hell"
        - type: command
          name: "lights off"
          command:
            - homeassistant.service:
                service: script.off_script
    - name: Settings Screen
      show_version: True
      entities:
        - id: backlight
          type: light
        - id: "restart_switch"
          type: switch
        - id: wifi_ssid
          type: text_sensor
        - id: wifi_signal_percent
          type: sensor
        - id: wifi_ip
          type: text_sensor