esphome:
  name: m5stickcplus
  on_boot:
    priority: 600.0
    then:
      - delay: 45s
      - if:
          condition:
            not:
              - wifi.connected:
          then:
            - switch.turn_on: sleep_toggle

esp32:
  board: m5stick-c
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_fallback_password

external_components:
  # - source:
  #     type: git
  #     url: https://github.com/esphome/esphome
  #     ref: dev
  #   components: [adc, i2s_audio, microphone]
  - source:
      type: git
      url: https://github.com/landonr/esphome-axp192
      ref: lando/add-charging-indicator
    # type: local
    # path: ../axp192/components
  - source:
      type: git
      url: https://github.com/landonr/homeThing
      ref: main
      # type: local
      # path: ../homeThing/components
    refresh: 0s
    components: [homeThing, homeThingDisplayState, homeThingApp, homeThingAppNowPlaying, homeThingAppCatToy ]
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
      # type: local
      # path: ../local_components/components
    refresh: 0s
    components: [
      homeassistant_component,
      homeassistant_media_player,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom,
      MiniEncoderC
    ]
  - source: github://pr#5214 # used to load images on compile
    components: [ image ]
  - source: github://pr#5254 # used to load fonts on compile
    components: [ font, external_files ]


packages:
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [
      common/device_base.yaml, # defines api, ota, free memory and uptime sensor
      common/fonts.yaml, # default font
      common/icon_fonts.yaml, # material icons
      common/m5stack-stickc/axp192-marty.yaml, # power management and screen backlight
      common/m5stack-stickc/sleep.yaml, # deep sleep
      common/m5stack-stickc/binary_sensor.yaml, # buttons
      common/m5stack-stickc/MiniEncoderC.yaml, # rotary encoder and built in led
      common/images.yaml # boot screen image
    ]
    refresh: 0s
  home_media_player: !include homeConfig/media_player_light.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  # device_base: !include ../homeThing/common/device_base.yaml
  # fonts: !include ../homeThing/common/fonts.yaml
  # icon_fonts: !include ../homeThing/common/icon_fonts.yaml
  # axp192: !include ../homeThing/common/m5stack-stickc/axp192.yaml # power management and screen backlight
  # sleep: !include ../homeThing/common/m5stack-stickc/sleep.yaml # deep sleep
  # binary_sensor: !include ../homeThing/common/m5stack-stickc/binary_sensor.yaml # buttons
  # mini_encoder_c: !include ../homeThing/common/m5stack-stickc/MiniEncoderC.yaml # rotary encoder and built in led

substitutions:
  friendly_name: "homeThingM5StickPlus"
  # log_level: DEBUG

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

homeThingDisplayState:
  id: display_state_id
  font_small: small_font
  font_medium: medium_font
  font_large: large_font
  font_large_heavy: large_heavy_font
  font_material_large: material_font_large
  font_material_small: material_font_small
  launch_image: launch_image
  draw_now_playing_bottom_menu: True

homeThingAppNowPlaying:
  id: now_playing
  media_player_group: media_group_component
  display: my_display
  display_state: display_state_id

homeThing:
  id: homeThingMenu
  apps: 
    - now_playing
  settings:
    mode: 3_button
  sleep_switch: sleep_toggle
  backlight: backlight
  display_state: display_state_id
  # battery:
  #   battery_percent: battery_percent
  #   charging: axp_charger
  display: my_display
  on_redraw:
    then:
      component.update: my_display

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 0
    update_interval: 3600s
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;

remote_receiver:
  pin: GPIO32
  dump: all

i2s_audio:
  id: bus_i2s
  i2s_lrclk_pin: G26
  i2s_bclk_pin: G0
microphone:
  - platform: i2s_audio
    i2s_din_pin: GPIO34
    i2s_audio_id: bus_i2s
    adc_type: external
    pdm: true
    id: mic
voice_assistant:
  microphone: mic