esphome:
  name: "online-font-test"

esp32:
  board: featheresp32

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  power_save_mode: HIGH


packages:
  # ipod_control_backlight: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_backlight.yaml
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [
      common/ipod/lilygo_tdisplay_ipod_backlight.yaml, # used for toggling backlight
    ]


external_components:
  # - source: github://pr#5214 # used to load images on compile
  #   components: [ image ]
  #   refresh: 0s
  # - source: github://pr#5254 # used to load fonts on compile
  #   components: [ font, external_files ]
  #   refresh: 0s
  - source:
      # type: git
      # url: https://github.com/landonr/esphome-components
      # ref: main
    # refresh: 0s
      type: local
      path: ../compile-online-image/esphome/components
    components: [
      font,
      external_files
    ]

font:
  - file: "fonts/Comic Sans MS.ttf"
    id: my_font
    size: 20

  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: roboto2
    size: 16

  - file: "fonts/tom-thumb.bdf"
    id: tomthumb

  - file: "https://github.com/landonr/homeThing/raw/main/fonts/iosevka.ttf"
    id: web_font
    size: 20

  - file:
      url: "https://github.com/landonr/homeThing/raw/main/fonts/iosevka.ttf"
      type: web
    id: web_font2
    size: 24

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90
    update_interval: 10s
    lambda: |-
      it.print(0, 0, id(my_font), "web font");
      it.print(0, 25, id(roboto), "web font medium");
      it.print(0, 50, id(roboto2), "local font");
      it.print(0, 75, id(tomthumb), "󰐊");
      it.print(0, 100, id(web_font), "web font");
      it.print(0, 125, id(web_font2), "web font2");
      return;