esphome:
  name: "oplilygos3"
  platformio_options:
    board_build.f_flash: 80000000L
    board_build.partitions: default_16MB.csv
    board_build.arduino.memory_type: qio_opi
  on_boot: 
    then:
    - delay: 5s
    - light.turn_on:
        id: backlight
        brightness: 100%

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
  flash_size: 16MB
  # framework:
  #   type: esp-idf
  #   version: recommended

# Enable logging
logger:
  logs:
    esp32.preferences: INFO
    component: ERROR
    sensor: INFO
    switch: INFO
    main: INFO
    binary_sensor: WARN
    text_sensor: WARN
    homething.menu.display: WARN
    homething.menu.base: INFO
    homething.boot: INFO
    homething.menu.control: INFO
    homething.menu.screen: INFO
    homething.animation: INFO
    homething.menu.text_helpers: INFO
    homething.nowplaying.control: WARN
    homeassistant.media_player_group: WARN
    homeassistant.component: WARN
    homeassistant.light: WARN
    homeassistant.switch: WARN
    homeassistant.text_sensor: WARN
    homeassistant.media_player_base: WARN
    homeassistant.media_player_tv: WARN
    cover: INFO
    light: INFO
    api: INFO
    voice_assistant: INFO
  level: DEBUG
  # hardware_uart: USB_SERIAL_JTAG
  # level: DEBUG

# Enable Home Assistant API
api:

ota:

substitutions:
  friendly_name: "s3 proto"
  rotary_pin_a: "10"
  rotary_pin_b: "11"
  medium_font_size: "17"
  # sda_pin: "18"
  # scl_pin: "17"
  # screen_left_pin: "GPIO0"
  # screen_right_pin: "GPIO14"
  battery_pin: "4"
  # log_level: "DEBUG"
  launch_image_size: 100x100
  launch_image_file: "s3.png"
  launch_image_type: "RGBA"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S3 Fallback Hotspot"
    password: "zQ9tuPKIfFMu"

external_components:
  - source:
      type: git
      url: https://github.com/landonr/homeThing
      ref: main
      # type: local
      # path: ../homething/components
    components: [homeThing, homeThingDisplayState, homeThingApp, homeThingAppNowPlaying, homeThingAppSnake, homeThingAppCatToy, homeThingAppBreakout, homeThingAppWeather]
    refresh: 0s
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
      # type: local
      # path: ../local_components/components
    components: [
      homeassistant_component,
      homeassistant_media_player,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]
    refresh: 0s
  - source: 
      type: git
      url: https://github.com/landonr/lilygo-tdisplays3-esphome/
      ref: main
    refresh: 0s
    components: [tdisplays3]
  - source: github://pr#5254 # used to load fonts on compile
  # - source:
  #     type: local
  #     path: ../compile-online-image/esphome/components/
    components: [ font ]
    refresh: 0s

packages:
  home_media_player: !include homeConfig/media_player.yaml
  home_switch: !include homeConfig/switch.yaml
  plant_text_sensors: !include homeConfig/text_sensor_plants.yaml
  weather: !include homeConfig/weather.yaml
  # device_base: !include ../homeThing/common/device_base.yaml
  # fonts: !include ../homeThing/common/fonts.yaml
  # icon_fonts: !include ../homeThing/common/icon_fonts.yaml
  # ipod_control_binary_sensor: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml
  # ipod_control_binary_sensor_pcf: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_binary_sensor_pcf.yaml
  # ipod_control_rotary: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_rotary.yaml
  # ipod_control_battery: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_battery.yaml
  # ipod_control_sleep: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_sleep.yaml
  # s3_backlight: !include ../homeThing/common/tdisplay-s3/backlight.yaml
  # settings: !include ../homeThing/common/settings.yaml
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [
      common/device_base.yaml, # defines api, ota, free memory and uptime sensor
      common/fonts.yaml, # default font
      common/icon_fonts.yaml, # material icons
      common/ipod/lilygo_tdisplay_ipod_battery.yaml, # used for battery percent
      common/ipod/lilygo_tdisplay_ipod_binary_sensor_pcf.yaml, # used for button controls
      common/ipod/lilygo_tdisplay_ipod_rotary.yaml, # used for rotary controls
      common/ipod/lilygo_tdisplay_ipod_sleep.yaml, # required for device to sleep
      common/tdisplay-s3/backlight.yaml, # backlight
      common/settings.yaml, # settings screen
      # common/images.yaml # boot screen image
    ]
    refresh: 0s

i2s_audio:
  i2s_lrclk_pin: 3 # WS
  i2s_bclk_pin: 2 # SCK
  # i2s_mclk_pin: GPIO8 # MCLK

microphone:
  - platform: i2s_audio
    id: external_mic
    i2s_din_pin: 1 # SD
    adc_type: external
    pdm: false
    # bits_per_sample: 32bit
    channel: left

voice_assistant:
  microphone: external_mic
  on_start:
    then:
      lambda: |-
        id(homeThingMenu)->clearNotifications();
        id(homeThingMenu)->addNotification("Voice Assistant", "Listening", "", true);
        return;
  on_error:
    then:
      lambda: |-
        id(homeThingMenu)->addNotification("Voice Assistant", "Error", message, false);
        return;
  on_stt_end:
    then:
      lambda: |-
        id(homeThingMenu)->addNotification("Voice Assistant", "Understood", x, false);
        return;
  on_tts_start:
    then:
      lambda: |-
        id(homeThingMenu)->addNotification("Voice Assistant", "Finished", x, true);
        return;

remote_transmitter:
  pin: GPIO12
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%
  id: infrared

light:
  - platform: homeassistant_component
    id: light_desk_lamp
    entity_id: light.desk_lamp
    name: Desk Lamp
  - platform: homeassistant_component
    id: light_all_lights
    entity_id: light.all_lights
    name: All Lights
  - platform: homeassistant_component
    id: light_rgb_lights
    entity_id: light.rgb_lights
    name: Color Lights 
  - platform: homeassistant_component
    id: light_track
    entity_id: light.kitchen_track_lights
    name: Track Lights
  - platform: homeassistant_component
    id: light_strip_light
    entity_id: light.homethingm5stickplus_strip_light
    name: Strip Light

display:
  - platform: tdisplays3
    id: my_display
    rotation: 180
    update_interval: 60s
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;

cover:
  - platform: homeassistant_component
    entity_id: "cover.megadesk_cover"
    name: "Megadesk"
    id: cover_megadesk

switch:
  - platform: homeassistant_component
    entity_id: "switch.oven_fan"
    name: "Oven Fan"
    id: oven_fan
  - platform: template
    id: dark_mode
    name: "Dark Mode"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
  - platform: output
    name: "${friendly_name} Light"
    id: lightSwitch
    output: lightOutput
    restore_mode: ALWAYS_ON
  - platform: template
    id: voice_assistant_switch
    name: ${friendly_name} Voice Assistant
    restore_mode: ALWAYS_OFF
    optimistic: true
    turn_on_action: 
      then:
        - voice_assistant.start:
    turn_off_action: 
      then:
        voice_assistant.stop:

output:
  - platform: gpio
    pin: 13
    id: lightOutput
    # inverted: True

homeThingDisplayState:
  id: display_state_id
  draw_battery_level: true
  font_small: small_font
  font_medium: medium_font
  font_large: large_font
  font_large_heavy: large_heavy_font
  font_material_large: material_font_large
  font_material_small: material_font_small
  launch_image: launch_image
  now_playing_max_lines: 10
  dark_mode: dark_mode
  colors:
    accent_primary: my_primary_accent

homeThingAppNowPlaying:
  id: now_playing
  media_player_group: media_group_component
  display: my_display
  display_state: display_state_id

homeThingAppSnake:
  id: snake
  display: my_display
  display_state: display_state_id

homeThingAppCatToy:
  id: cat_toy
  remote_transmitter: infrared
  display: my_display
  display_state: display_state_id

homeThingAppBreakout:
  id: breakout
  display: my_display
  display_state: display_state_id

color:
  - id: my_primary_accent
    red_int: 106
    green_int: 43
    blue_int: 138

homeThingAppWeather:
  id: weather
  display: my_display
  display_state: display_state_id
  temperature_sensor: weather_temperature
  humidity_sensor: weather_humidity
  condition_sensor: weather_state
  images:
    cloudy: weather_cloudy
    fog: weather_fog
    snow: weather_snow
    sunny: weather_sunny
    rainy: weather_rainy
    night: weather_night

homeThing:
  id: homeThingMenu
  apps: 
    - now_playing
    - breakout
    - snake
    - cat_toy
    - weather
  settings:
    sleep_after: 14400
    display_timeout_while_charging: 30
    idle_app: now_playing
  backlight: backlight
  header:
    time_id: esptime
  sleep_switch: sleep_toggle
  battery:
    battery_percent: battery_percent
    charging: charging
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state: display_state_id
  boot:
    api_connected: api_connected
    media_players_loaded: media_players_loaded_sensor
  home_screen:
    name: root
    entities:
      # - id: lightSwitch
      #   type: switch
      - id: light_rgb_lights
        type: light
      - type: command
        name: "feed lil freak"
        command:
          - homeassistant.service:
              service: button.press
              data:
                entity_id: "button.catfeeder_node_feed_single"
      - type: switch
        id: oven_fan
  screens:
    - name: Desk Screen
      entities:
        - type: cover
          id: cover_megadesk
        - type: command
          name: "desk nudge up"
          command:
            - homeassistant.service:
                service: button.press
                data:
                  entity_id: "button.mega_homething_desk_position_nudge_up"
        - type: command
          name: "desk nudge down"
          command:
            - homeassistant.service:
                service: button.press
                data:
                  entity_id: "button.mega_homething_desk_position_nudge_down"
        - id: light_desk_lamp
          type: light
    - name: Plants
      entities:
        - type: text_sensor
          id: sensor_plant_temp
        - type: text_sensor
          id: sensor_plant_humidity
        - type: text_sensor
          id: sensor_plant_fan
    - name: Lights Screen
      entities:
        - id: light_all_lights
          type: light
        - id: light_rgb_lights
          type: light
        - id: light_track
          type: light
        - id: light_strip_light
          type: light
        - type: command
          name: "color scene"
          command:
            - homeassistant.service:
                service: script.warm
        - type: command
          name: "auto scene"
          command:
            - homeassistant.service:
                service: script.auto
        - type: command
          name: "hell scene"
          command:
            - homeassistant.service:
                service: scene.turn_on
                data:
                  entity_id: "scene.hell"
        - type: command
          name: "lights off"
          command:
            - homeassistant.service:
                service: script.off_script
    - name: Settings Screen
      show_version: True
      entities:
        - id: dark_mode
          type: switch
        - id: backlight
          type: light
        - id: restart_switch
          type: switch
        - id: wifi_ssid
          type: text_sensor
        - id: wifi_signal_percent
          type: sensor
        - id: wifi_ip
          type: text_sensor