esphome:
  name: proto_tdisplay
  platform: ESP32
  board: featheresp32
  on_boot:
    priority: 600.0
    then:
      - delay: 45s
      - if:
          condition:
            not:
              - wifi.connected:
          then:
            - switch.turn_on: sleep_toggle

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_fallback_password

external_components:
  - source:
      type: git
      url: https://github.com/landonr/homeThing
      ref: main
      # type: local
      # path: ../homething/components
    components: [homeThing, homeThingDisplayState, homeThingApp, homeThingAppNowPlaying, homeThingAppSnake]
    refresh: 0s
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
      # type: local
      # path: ../local_components/components
    components: [
      homeassistant_component,
      homeassistant_media_player,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]
    refresh: 0s
  # - source: github://pr#5214 # used to load images on compile
    # components: [ image ]
    # refresh: 0s
  - source: github://pr#5254 # used to load fonts on compile
    components: [ font ]
    refresh: 0s

packages:
  # device_base: !include ../homeThing/common/device_base.yaml
  # ipod_control_backlight: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_backlight.yaml
  # ipod_control_battery: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_battery.yaml
  # ipod_control_binary_sensor: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml
  # ipod_control_rotary: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_rotary.yaml
  # ipod_control_sleep: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_sleep.yaml
  # fonts: !include ../homeThing/common/fonts.yaml
  # icon_fonts: !include ../homeThing/common/icon_fonts.yaml
  home_media_player: !include homeConfig/media_player_light.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [
      common/device_base.yaml, # defines api, ota, free memory and uptime sensor
      common/ipod/lilygo_tdisplay_ipod_backlight.yaml, # used for toggling backlight
      # common/ipod/lilygo_tdisplay_ipod_battery.yaml, # used for battery percent
      common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml, # used for button controls
      common/ipod/lilygo_tdisplay_ipod_rotary.yaml, # used for rotary controls
      common/ipod/lilygo_tdisplay_ipod_sleep.yaml, # required for device to sleep
      common/fonts.yaml, # default font
      common/icon_fonts.yaml, # material icons
      common/images.yaml # boot screen image
      # common/settings.yaml, # settings screen
    ]
    refresh: 0s

substitutions:
  friendly_name: "homeThing proto"
  rotary_pin_a: "12"
  rotary_pin_b: "13"
  rotary_select_pin: "15"
  rotary_down_pin: "2"
  rotary_right_pin: "17"
  rotary_up_pin: "22"
  rotary_left_pin: "21"

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

homeThingAppNowPlaying:
  id: now_playing
  media_player_group: media_group_component
  display: my_display
  display_state: display_state_id

homeThingAppSnake:
  id: snake
  display: my_display
  display_state: display_state_id

homeThingDisplayState:
  id: display_state_id
  draw_battery_level: true
  font_small: small_font
  font_medium: medium_font
  font_large: large_font
  font_large_heavy: large_font
  font_material_large: material_font_large
  font_material_small: material_font_small
  launch_image: launch_image

homeThing:
  id: homeThingMenu
  settings:
    sleep_after: 14400
    display_timeout: 8
    display_timeout_while_charging: 8
  # sleep_switch: sleep_toggle
  backlight: backlight
  # battery:
  #   battery_percent: battery_percent
  #   charging: charging
  display: my_display
  display_state: display_state_id
  on_redraw:
    then:
      component.update: my_display
  apps:
    - now_playing
    - snake
  header:
    time_id: esptime
  boot:
    api_connected: api_connected
    media_players_loaded: media_players_loaded_sensor
  home_screen:
    name: root
    entities:
      - id: dark_mode
        type: switch
      - id: light_rgb_lights
        type: light

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    backlight_pin: no
    rotation: 90
    update_interval: 10s
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;

