esphome:
  name: "white-homething"
  on_boot:
    priority: 600.0
    then:
      - delay: 45s
      - if:
          condition:
            not:
              - wifi.connected:
          then:
            - switch.turn_on: sleep_toggle

esp32:
  board: featheresp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  power_save_mode: HIGH

external_components:
  - source:
      type: git
      url: https://github.com/landonr/homeThing
      ref: main
      # type: local
      # path: ../homething/components
    components: [
      homeThing, 
      homeThingDisplayState, 
      homeThingApp, 
      homeThingAppNowPlaying, 
      # homeThingAppSnake, 
      # homeThingAppBreakout, 
      homeThingAppWeather 
    ]
    refresh: 0s
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
      # type: local
      # path: ../local_components/components
    components: [
      homeassistant_component,
      homeassistant_media_player,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]
    refresh: 0s
  # - source: github://pr#5214
  # - source: # used to load images on compile
  #     type: local
  #     path: ../compile-online-image/esphome/components/
  #   components: [ image ]
  #   refresh: 0s
  - source: github://pr#5254
  # - source: # used to load fonts on compile
      # type: local
      # path: ../compile-online-image/esphome/components/
    components: [ font ]
    refresh: 0s

packages:
  home_media_player: !include homeConfig/media_player_light.yaml
  # home_media_player: !include homeConfig/media_player.yaml
  # home_switch: !include homeConfig/switch.yaml
  # device_base: !include ../homeThing/common/device_base.yaml
  # ipod_control_backlight: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_backlight.yaml
  # ipod_control_battery: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_battery.yaml
  # ipod_control_binary_sensor: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml
  # ipod_control_rotary: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_rotary.yaml
  # ipod_control_sleep: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_sleep.yaml
  # fonts-light: !include ../homeThing/common/fonts-light.yaml
  # fonts: !include ../homeThing/common/fonts.yaml
  # icon_fonts: !include ../homeThing/common/icon_fonts.yaml
  fonts_local: !include ../homeThing/common/fonts-local.yaml
  icon_fonts_local: !include ../homeThing/common/icon_fonts-local.yaml
  # settings: !include ../homeThing/common/settings.yaml
  # images: !include ../homeThing/common/images.yaml
  # debug: !include ../homeThing/common/debugging.yaml
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [
      common/device_base.yaml, # defines api, ota, free memory and uptime sensor
      common/ipod/lilygo_tdisplay_ipod_backlight.yaml, # used for toggling backlight
      # common/ipod/lilygo_tdisplay_ipod_battery.yaml, # used for battery percent
      common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml, # used for button controls
      common/ipod/lilygo_tdisplay_ipod_rotary.yaml, # used for rotary controls
      common/ipod/lilygo_tdisplay_ipod_sleep.yaml, # required for device to sleep
      # common/fonts-local.yaml, # default font
      # common/icon_fonts-local.yaml, # material icons
      common/settings.yaml, # settings screen
      # common/images.yaml, # boot screen image
      common/debugging.yaml # debug
    ]
    refresh: 0s

substitutions:
  friendly_name: "white homething"
  # log_level: DEBUG

color:
  - id: my_primary_accent
    red_int: 55
    green_int: 35
    blue_int: 229

light:
  - platform: homeassistant_component
    id: light_rgb_lights
    entity_id: light.rgb_lights
    name: Color Lights 

switch:
  - platform: template
    id: dark_mode
    name: "Dark Mode"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on: 
      then:
        media_player.power: media_group_component

number:
  - platform: template
    id: test_number
    name: "Test Number"
    min_value: 0
    max_value: 100
    step: 5
    optimistic: true
    internal: true

homeThingDisplayState:
  id: display_state_id
  draw_battery_level: true
  font_small: small_font
  font_medium: medium_font
  font_large: large_font
  font_large_heavy: large_font
  font_material_large: material_font_large
  font_material_small: material_font_small
  launch_image: launch_image
  dark_mode: dark_mode
  draw_now_playing_bottom_menu: false
  colors:
    accent_primary: my_primary_accent

homeThingAppNowPlaying:
  id: now_playing
  media_player_group: media_group_component
  display: my_display
  display_state: display_state_id
  # up_button: sw4

# homeThingAppSnake:
#   id: snake
#   display: my_display
#   display_state: display_state_id
  # up_button: sw4

# homeThingAppBreakout:
#   id: breakout
#   display: my_display
#   display_state: display_state_id

image:
  - file: mdi:weather-cloudy
    id: weather_cloudy
    resize: 50x50
  - file: mdi:weather-fog
    id: weather_fog
    resize: 50x50
  - file: mdi:weather-snowy
    id: weather_snow
    resize: 50x50
  - file: mdi:weather-sunny
    id: weather_sunny
    resize: 50x50
  - file: mdi:weather-rainy
    id: weather_rainy
    resize: 50x50
  - file: mdi:weather-night
    id: weather_night
    resize: 50x50
  - id: launch_image
    # file: https://avatars.githubusercontent.com/u/2607659?s=64
    # file: "https://raw.githubusercontent.com/landonr/homeThing/main/docs/homeThingLogo.svg"
    # file: "https://raw.githubusercontent.com/landonr/homeThing/main/docs/lights.jpg"
    # file: "http://cloud.ine.ru/s/JDbPr6W4QXnXKgo/download"
    # file: "http://172.16.1.67:8123/api/media_player_proxy/media_player.beam?token=a955fc758234e7ac5d9e484b5dc401970113a347dc2de2c5f4f1a70ab4fde614&cache=45ec98127e9e4fe0"
    file: https://upload.wikimedia.org/wikipedia/commons/b/b6/SIPI_Jelly_Beans_4.1.07.tiff
    resize: 64x64
    type: RGB24
    

sensor:
  - platform: homeassistant
    id: weather_temperature
    entity_id: weather.accuweather
    attribute: temperature
  - platform: homeassistant
    id: weather_humidity
    entity_id: weather.accuweather
    attribute: humidity

text_sensor:
  - platform: homeassistant
    entity_id: "sensor.weather_condition"
    name: "Weather state"
    id: weather_state

homeThingAppWeather:
  id: weather
  display: my_display
  display_state: display_state_id
  temperature_sensor: weather_temperature
  humidity_sensor: weather_humidity
  condition_sensor: weather_state
  images:
    cloudy: weather_cloudy
    fog: weather_fog
    snow: weather_snow
    sunny: weather_sunny
    rainy: weather_rainy
    night: weather_night

homeThing:
  id: homeThingMenu
  settings:
    sleep_after: 14400
    display_timeout_while_charging: 30
    idle_app: weather
  sleep_switch: sleep_toggle
  backlight: backlight
  boot:
    api_connected: api_connected
    media_players_loaded: media_players_loaded_sensor
  header:
    time_id: esptime
  # battery:
  #   battery_percent: battery_percent
  #   charging: charging
  apps: 
    - weather
    - now_playing
    # - snake
    # - breakout
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state: display_state_id
  home_screen:
    name: root
    entities:
      - id: dark_mode
        type: switch
      - id: light_rgb_lights
        type: light
  screens:
    - name: Desk Screen
      entities:
        - type: command
          name: "desk nudge up"
          command:
            - homeassistant.service:
                service: button.press
                data:
                  entity_id: "button.desk_position_nudge_up"
        - type: command
          name: "desk nudge down"
          command:
            - homeassistant.service:
                service: button.press
                data:
                  entity_id: "button.desk_position_nudge_down"
    - name: Lights Screen
      entities:
        - id: light_rgb_lights
          type: light
        - type: command
          name: "color lights"
          command:
            - homeassistant.service:
                service: script.colors
        - type: command
          name: "hell lights"
          command:
            - homeassistant.service:
                service: scene.turn_on
                data:
                  entity_id: "scene.hell"
        - type: command
          name: "lights off"
          command:
            - homeassistant.service:
                service: script.off_script
    - name: Settings Screen
      show_version: True
      entities:
        - id: backlight
          type: light
        - id: "restart_switch"
          type: switch
        - id: wifi_ssid
          type: text_sensor
        - id: wifi_signal_percent
          type: sensor
        - id: wifi_ip
          type: text_sensor
        - id: test_number
          type: number

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90
    update_interval: 3600s
    backlight_pin: no
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;
    